version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_USER=user
      - MONGO_PASSWORD=1234
      - MONGO_DATABASE_NAME=mongo
      - MONGO_PORT=27017
    volumes:
      - mongo_data:/data/db

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://user:1234@mongo:27017

  books:
    build:
      context: .
      dockerfile: ./books/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://user:1234@mongo:27017

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - books

volumes:
  mongo_data:
