version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME} # Добавлено для явного указания базы данных
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand(\"ping\").ok'"]
      interval: 5s
      timeout: 5s
      retries: 5

  #  migration:  ## MongoDB, как правило, не нуждается в миграциях в том же смысле, что и SQL базы данных.
  #    build:      ## Вместо этого, можно использовать скрипты для создания индексов или начальной загрузки данных.
  #      context: .
  #      dockerfile: migration.Dockerfile
  #    depends_on:
  #      mongodb:
  #        condition: service_healthy
  #    environment:
  #      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE_NAME} # Строка подключения
  #      #MONGO_INIT_SCRIPT: /path/to/your/init_script.js # Пример пути к скрипту инициализации

volumes:
  mongodb_data: